---
title: 'Final project'
output: github_document
---

```{r}
library(tidyverse)
library(GGally)
library(patchwork)
library(gt)
library(leaps)
library(caret)
library(readxl)
library(patchwork)
library(glmnet)
```

```{r}
body_density_df = read_excel("data/body_density_data.xlsx") %>%
  rename(outcome = bodyfat_brozek) %>% 
  select(-bodyfat_siri & -body_density)
head(body_density_df)
```

Descriptive statistics:

```{r}
body_density_df %>%
  gtsummary::tbl_summary() %>%
  gtsummary::bold_labels()

summary(body_density_df)
```

Exploratory plots

```{r}
body_density_df %>%
  relocate(outcome) %>%
  ggpairs()
```

Histogram plots

```{r}
hist1 = body_density_df %>% 
  ggplot(aes(x = age)) +
  geom_histogram()
hist2 = body_density_df %>% 
  ggplot(aes(x = weight)) +
  geom_histogram()
hist3 = body_density_df %>% 
  ggplot(aes(x = height)) +
  geom_histogram()

hist1 + hist2 + hist3

hist4 = body_density_df %>% 
  ggplot(aes(x = neck)) +
  geom_histogram()
hist5 = body_density_df %>% 
  ggplot(aes(x = chest)) +
  geom_histogram()
hist6 = body_density_df %>% 
  ggplot(aes(x = abdomen)) +
  geom_histogram()

hist4 + hist5 + hist6

hist7 = body_density_df %>% 
  ggplot(aes(x = hip)) +
  geom_histogram()
hist8 = body_density_df %>% 
  ggplot(aes(x = thigh)) +
  geom_histogram()
hist9 = body_density_df %>% 
  ggplot(aes(x = knee)) +
  geom_histogram()

hist7 + hist8 + hist9

hist10 = body_density_df %>% 
  ggplot(aes(x = ankle)) +
  geom_histogram()
hist11 = body_density_df %>% 
  ggplot(aes(x = bicep)) +
  geom_histogram()
hist12 = body_density_df %>% 
  ggplot(aes(x = forearm)) +
  geom_histogram()

hist10 + hist11 + hist12

hist13 = body_density_df %>% 
  ggplot(aes(x = wrist)) +
  geom_histogram()

hist13
```

## Fitting a full model and checking diagnostic plots

```{r}
full_model = lm(outcome ~ ., data = body_density_df)
summary(full_model)

par(mfrow = c(2,2))
plot(full_model)
```

The diagnostics plots look good. No need for Box-Cox transformation

## Forward selection

```{r}
intercept_only <- lm(outcome ~ 1, data = body_density_df)
fit_forward = step(intercept_only, direction = "forward", scope = formula(full_model))
summary(fit_forward)
```

## Backward Elimination

```{r}
fit_backward = step(lm(full_model, data = body_density_df), direction = "backward")
summary(fit_backward) 
```

## Stepwise selection

```{r}
step(
lm(outcome ~ age + weight + height + neck + chest + abdomen + hip + knee + ankle + bicep + forearm + wrist,
data = body_density_df),
direction = "both"
) %>% 
summary()
```

## Criteria-based Selection

```{r}
b = regsubsets(outcome ~ 
                 age + weight + height + neck + chest + abdomen + hip + thigh +
                 knee + ankle + bicep + forearm + wrist, data = body_density_df)
rs = summary(b)

par(mfrow=c(1,2))
plot(2:9, rs$cp, xlab = "No of parameters", ylab = "Cp Statistic")
abline(0,1)
   
plot(2:9, rs$adjr2, xlab = "No of parameters", ylab = "Adj R2")
par(mfrow = c(1,1))
```

```{r}
## cp_model <- leaps(x = as.matrix(body_density_df)[,c(3:15)], y = as.matrix(body_density_df)[,2], nbest = 1, method = "Cp")
## colnames(as.matrix(body_density_df)[,c(3:15)])[which(cp_model$which[9,])]
```

## Lasso

```{r}
new_df = body_density_df %>% 
  select(-id)
# using cross validation to choose lambda
lambda_seq <- 10^seq(-3, 0, by = .1)
set.seed(2022)
cv_object <- glmnet::cv.glmnet(as.matrix(new_df[2:14]), new_df$outcome, 
                       lambda = lambda_seq, 
                       nfolds = 10)
cv_object 

# plot the CV results
tibble(lambda = cv_object$lambda,
       mean_cv_error = cv_object$cvm) %>%
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point()

# extracting the exact minimum lambda from the CV object
cv_object$lambda.min


# refit the lasso model with the "best" lambda
fit_bestcv <- glmnet::glmnet(as.matrix(new_df[2:14]), new_df$outcome, lambda = cv_object$lambda.min)
coef(fit_bestcv)
```


## RIDGE

```{r}
lambda_seq <- 10^seq(-3, 0, by = .1)
  
cv_object <- glmnet::cv.glmnet(as.matrix(new_df[2:14]), new_df$outcome, 
                               lambda = lambda_seq, alpha = 0,
                               nfolds = 10)
cv_object

tibble(lambda = cv_object$lambda,
       mean_cv_error = cv_object$cvm) %>%
  ggplot(aes(x = lambda, y = mean_cv_error)) +
  geom_point()

lambda_min = cv_object$lambda.min
ridge_fit <- glmnet::glmnet(as.matrix(new_df[2:14]), new_df$outcome, 
                            lambda = lambda_min, alpha = 0)
coef(ridge_fit)
```






